# Generated by Django 6.0.3 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('data_nasc', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=20)),
                ('nível', models.CharField(choices=[('I', 'Intermediario'), ('A', 'Avançado'), ('B', 'Básico')], default='B', max_length=40)),
            ],
        ),
    ]
